import React from "react";
import Swiper from "react-id-swiper";
import { BigThumb } from "../../atom/Image/Image";
import "./Fraction.scss";

export const Fraction = () => {
  const imgArr = [
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
    { src: "/img/chicken.png" },
  ];

  const params = {
    pagination: {
      el: ".swiper-pagination.fraction_thumb",
      type: "fraction",
    },
  };

  return (
    <Swiper {...params}>
      {imgArr.map((e, index) => {
        return (
          <div key={index}>
            <BigThumb src={e.src} />
          </div>
        );
      })}
    </Swiper>
  );
};
